services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    env_file: .env
    ports:
      - "127.0.0.1:8002:8002"
    volumes:
      - .:/app
      - ./logs:/logs

  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    env_file: .env
    volumes:
      - .:/bot
      - ./logs:/logs
